device: cuda

image_shape: [3, 224, 224]

num_keypoints: 7
keypoints_shape: [?, ?, ?]

classifier_free_guidance:
  enable: true
  scale: 1.0
  discard_conditioning_probability: 0.1

timestep_embedder:
  encoding_dim: 128
  hidden_dim: 128
  output_dim: 128
  activation: nn.SiLU

condition_embedder:
  hidden_dim: 512
  output_dim: 512
  activation: nn.SiLU

diffuser:
  sampler: ddpm
  timesteps: 100

unet:
  hidden_dims: [128, 256, 512]
  activation: nn.SiLU
